ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  enabled: true
  className: nginx
  host: saas-hml.undistro.io
  tlsSecretName: zora-saas-cert
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
imagePullSecrets:
  - name: zora-saas-registry-cred
storage: "mongo"
mongo:
  database: "zora-saas-hml"
